# SPDX-License-Identifier: GPL-2.0-only
# BCM2835 Platform Support
#snd-soc-bcm2835-i2s-objs := bcm2835-i2s.o

#obj-$(CONFIG_SND_BCM2835_SOC_I2S) += snd-soc-bcm2835-i2s.o

#snd-soc-bcm2835-pdm-objs := bcm2835-pdm-3072.o

#obj-$(CONFIG_SND_BCM2835_SOC_I2S) += snd-soc-bcm2835-pdm.o


snd-soc-bcm2835-pdm2-objs := bcm2835-pdm-1536.o

obj-$(CONFIG_SND_BCM2835_SOC_I2S) += snd-soc-bcm2835-pdm2.o


#bcm2835-pdm-3072.o bcm2835-pdm-1536.o

# CYGNUS Platform Support
snd-soc-cygnus-objs := cygnus-pcm.o cygnus-ssp.o

obj-$(CONFIG_SND_SOC_CYGNUS) += snd-soc-cygnus.o

# BCM63XX Platform Support
snd-soc-63xx-objs := bcm63xx-i2s-whistler.o bcm63xx-pcm-whistler.o

obj-$(CONFIG_SND_BCM63XX_I2S_WHISTLER) += snd-soc-63xx.o
